/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagementsystem.student;

import collegemanagementsystem.model.CourseModel;
import collegemanagementsystem.model.DepratmentModel;
import collegemanagementsystem.model.Enrollment;
import collegemanagementsystem.model.FacultyModel;
import collegemanagementsystem.model.Staff;
import database.DatabaseHandler;
import javax.swing.JOptionPane;

public class SearchStudentPersonalInfo extends javax.swing.JFrame {

    String selectedTableName = "courses";
    public SearchStudentPersonalInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sname = new javax.swing.JLabel();
        searchingCombobox = new javax.swing.JComboBox();
        searchLabel = new javax.swing.JLabel();
        searchStudent_searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        searchStudent_backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sname.setText("Searching Using");

        searchingCombobox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchingCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Courses", "Exam Scores", "Department", "Faculty" }));
        searchingCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchingComboboxActionPerformed(evt);
            }
        });

        searchLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchLabel.setText("Enter ID");

        searchStudent_searchField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        searchBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        searchStudent_backBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchStudent_backBtn.setText("Back");
        searchStudent_backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudent_backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchStudent_backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sname, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchingCombobox, 0, 291, Short.MAX_VALUE)
                            .addComponent(searchStudent_searchField))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchingCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchStudent_searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(searchStudent_backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchingComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchingComboboxActionPerformed
        // TODO add your handling code here:
        searchStudent_searchField.setText("");
        int selectedIndex = searchingCombobox.getSelectedIndex();
        switch (selectedIndex) {
            case 0:
                searchLabel.setText("Enter courseID");
                selectedTableName = "courses";
                break;

            case 1:
                searchLabel.setText("Enter Exam 1 Score");
                selectedTableName = "enrollement";
                break;

            case 2:
                searchLabel.setText("Enter Department Name");
                selectedTableName = "department";
                break;

            case 3:
                searchLabel.setText("Enter Faculty name");
                selectedTableName ="faculty";
                break;

        }

    }//GEN-LAST:event_searchingComboboxActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
       Object object = new DatabaseHandler().searchStudent(selectedTableName,searchStudent_searchField.getText().toString());
       if(object != null){
           if(object instanceof CourseModel){
               CourseModel course = (CourseModel)object;
               JOptionPane.showMessageDialog(this, course.toString());
           }else if(object instanceof DepratmentModel){
               DepratmentModel department = (DepratmentModel) object;
               JOptionPane.showMessageDialog(this, department.toString());
           }else if(object instanceof Enrollment){
               Enrollment model = (Enrollment) object;
               JOptionPane.showMessageDialog(this, model.toString());
           }else if(object instanceof FacultyModel){
               FacultyModel model = (FacultyModel) object;
               JOptionPane.showMessageDialog(this, model.toString());
           }else if(object instanceof Staff){
               Staff model = (Staff) object;
               JOptionPane.showMessageDialog(this, model.toString());
           }else if(object instanceof StudentEnrollment){
               StudentEnrollment model = (StudentEnrollment) object;
               JOptionPane.showMessageDialog(this, model.toString());
           }
       }else{
           JOptionPane.showMessageDialog(this, "No Record Found !");
       }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchStudent_backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudent_backBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StudentMenu().setVisible(true);
    }//GEN-LAST:event_searchStudent_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchStudentPersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchStudentPersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchStudentPersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchStudentPersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchStudentPersonalInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JButton searchStudent_backBtn;
    private javax.swing.JTextField searchStudent_searchField;
    private javax.swing.JComboBox searchingCombobox;
    private javax.swing.JLabel sname;
    // End of variables declaration//GEN-END:variables
}
