/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package collegemanagementsystem.student;

import collegemanagementsystem.model.Enrollment;
import collegemanagementsystem.model.StudentModel;
import database.DatabaseHandler;
import javax.swing.JOptionPane;

/**
 *
 * @author Sheraz Ali
 */
public class StudentEnrollment extends javax.swing.JFrame {

    DatabaseHandler database = new DatabaseHandler();
    public StudentEnrollment() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sname = new javax.swing.JLabel();
        sidTextField = new javax.swing.JTextField();
        cidTextField = new javax.swing.JTextField();
        sname1 = new javax.swing.JLabel();
        enrollInCourseBtn = new javax.swing.JButton();
        exam1TextField = new javax.swing.JTextField();
        sname2 = new javax.swing.JLabel();
        exam2TextField = new javax.swing.JTextField();
        sname3 = new javax.swing.JLabel();
        sname4 = new javax.swing.JLabel();
        finalTextField = new javax.swing.JTextField();
        enrollStudentBackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Menu - Enrollment");

        sname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sname.setText("StudentId");

        sname1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sname1.setText("cid");

        enrollInCourseBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enrollInCourseBtn.setText("Enroll In Course");
        enrollInCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollInCourseBtnActionPerformed(evt);
            }
        });

        sname2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sname2.setText("exam1");

        sname3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sname3.setText("exam2");

        sname4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sname4.setText("final");

        enrollStudentBackBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enrollStudentBackBtn.setText("Back");
        enrollStudentBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollStudentBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(sidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(sname1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(cidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(sname2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(exam1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(sname3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(exam2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(sname4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(finalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(enrollInCourseBtn))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(enrollStudentBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(sidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sname1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sname2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exam1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sname3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exam2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sname4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(finalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(enrollInCourseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enrollStudentBackBtn))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enrollInCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollInCourseBtnActionPerformed
        // TODO add your handling code here:
        int sid = Integer.parseInt(sidTextField.getText().toString());
        String cid = cidTextField.getText().toString();
        int exam1 = Integer.parseInt(exam1TextField.getText().toString());
        int exam2 = Integer.parseInt(exam2TextField.getText().toString());
        int finals = Integer.parseInt(finalTextField.getText().toString());
        
        if(sidTextField.getText().toString().isEmpty() || cidTextField.getText().toString().isEmpty() 
                || exam1TextField.getText().toString().isEmpty() || exam2TextField.getText().toString().isEmpty()
                || finalTextField.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(this, "Empty Data Not Acceptable");
            return;
        }else{
            Enrollment enroll = new Enrollment(sid, cid, exam1, exam2, finals);
            database.addEnrollement(enroll);
            JOptionPane.showMessageDialog(this, "Student "+sid+" is enrolled in "+cid);
        }
        
    }//GEN-LAST:event_enrollInCourseBtnActionPerformed

    private void enrollStudentBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollStudentBackBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StudentMenu().setVisible(true);
    }//GEN-LAST:event_enrollStudentBackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentEnrollment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cidTextField;
    private javax.swing.JButton enrollInCourseBtn;
    private javax.swing.JButton enrollStudentBackBtn;
    private javax.swing.JTextField exam1TextField;
    private javax.swing.JTextField exam2TextField;
    private javax.swing.JTextField finalTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField sidTextField;
    private javax.swing.JLabel sname;
    private javax.swing.JLabel sname1;
    private javax.swing.JLabel sname2;
    private javax.swing.JLabel sname3;
    private javax.swing.JLabel sname4;
    // End of variables declaration//GEN-END:variables
}
