/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagementsystem.student;

import collegemanagementsystem.staff.StaffMenus;

/**
 *
 * @author AR
 */
public class StudentMenu extends javax.swing.JFrame {

    /**
     * Creates new form StudentMenu
     */
    public StudentMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enrollStudentBtn = new javax.swing.JButton();
        searchStudentPersonalInfoBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        studentMenuExitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enrollStudentBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enrollStudentBtn.setText("Enroll Student in course");
        enrollStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollStudentBtnActionPerformed(evt);
            }
        });

        searchStudentPersonalInfoBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchStudentPersonalInfoBtn1.setText("Search Student Personal Information");
        searchStudentPersonalInfoBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudentPersonalInfoBtn1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("College Management System -  Student Menu");

        studentMenuExitbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentMenuExitbtn.setText("Exit and Close");
        studentMenuExitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentMenuExitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enrollStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchStudentPersonalInfoBtn1)
                    .addComponent(jLabel1))
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(studentMenuExitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(searchStudentPersonalInfoBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(enrollStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentMenuExitbtn)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enrollStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollStudentBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StudentEnrollment().setVisible(true);
    }//GEN-LAST:event_enrollStudentBtnActionPerformed

    private void searchStudentPersonalInfoBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentPersonalInfoBtn1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new SearchStudentPersonalInfo().setVisible(true);
    }//GEN-LAST:event_searchStudentPersonalInfoBtn1ActionPerformed

    private void studentMenuExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentMenuExitbtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_studentMenuExitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduceenrollStudentable, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enrollStudentBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton searchStudentPersonalInfoBtn1;
    private javax.swing.JButton studentMenuExitbtn;
    // End of variables declaration//GEN-END:variables
}
