/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagementsystem.staff;

import collegemanagementsystem.model.CourseModel;
import collegemanagementsystem.model.DepratmentModel;
import database.DatabaseHandler;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AR
 */
public class DepartmentCRUD extends javax.swing.JFrame {

    /**
     * Creates new form DepartmentCRUD
     */
    int row;
    DatabaseHandler db = new DatabaseHandler();
    public DepartmentCRUD() {
        initComponents();
        loadJTable();
    }

      public void loadJTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        List<DepratmentModel> list = db.getAllDepartment();
        Object rowData[] = new Object[2];
        for (int i = 0; i < list.size(); i++) {
            rowData[0] = list.get(i).getDid();
            rowData[1] = list.get(i).getDname();
            model.addRow(rowData);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addDeptBtn = new javax.swing.JButton();
        deleteDeptBtn = new javax.swing.JButton();
        updateDeptBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deptIDTextField = new javax.swing.JTextField();
        deptNameTextField = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        departmentCrud_backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Department ID", "Department Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        addDeptBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addDeptBtn.setText("Add Department");
        addDeptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDeptBtnActionPerformed(evt);
            }
        });

        deleteDeptBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteDeptBtn.setText("Delete Department");
        deleteDeptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDeptBtnActionPerformed(evt);
            }
        });

        updateDeptBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateDeptBtn.setText("Update Department");
        updateDeptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDeptBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Dept Id");

        deptIDTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        deptNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search.setText("Search Department");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        departmentCrud_backBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        departmentCrud_backBtn.setText("Back");
        departmentCrud_backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentCrud_backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deptNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(deptIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(departmentCrud_backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addDeptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(search)
                            .addComponent(updateDeptBtn))
                        .addGap(165, 165, 165)
                        .addComponent(deleteDeptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deptIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deptNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDeptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateDeptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteDeptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(departmentCrud_backBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        row = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        deptIDTextField.setText(model.getValueAt(row, 0).toString());
        deptNameTextField.setText(model.getValueAt(row, 1).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void addDeptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDeptBtnActionPerformed
        // TODO add your handling code here:
        String ID = deptIDTextField.getText().toString();
        String Name = deptNameTextField.getText().toString();
        

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (ID.isEmpty() || Name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Empty Data Not Acceptable");
        } else {
            int did = Integer.parseInt(ID);

            new DatabaseHandler().addDepartmnet(new DepratmentModel(did, Name));
            model.addRow(new Object[]{did ,Name});
            JOptionPane.showMessageDialog(null, "Department Added Successfully !");
        }
    }//GEN-LAST:event_addDeptBtnActionPerformed

    private void deleteDeptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDeptBtnActionPerformed
        // TODO add your handling code here:
        String ID = deptIDTextField.getText().toString();
        if(ID.isEmpty()){
            JOptionPane.showMessageDialog(null, "Empty Data Acceptable !");
        }else{
            new DatabaseHandler().deleteDepartment(Integer.parseInt(ID));
            JOptionPane.showMessageDialog(null, "Department Deleted Successfully !");
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.removeRow(row);

        }
    }//GEN-LAST:event_deleteDeptBtnActionPerformed

    private void updateDeptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDeptBtnActionPerformed
        // TODO add your handling code here:

        String ID = deptIDTextField.getText().toString();
        String name = deptNameTextField.getText().toString();
        

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.removeRow(row);

        model.addRow(new Object[]{ID, name});

        if (ID.isEmpty() || name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Empty Data Acceptable !");
        } else {
            new DatabaseHandler().updateDepartment(new DepratmentModel(Integer.parseInt(ID), name));
            JOptionPane.showMessageDialog(null, "Department Updated Successfully !");
        }
    }//GEN-LAST:event_updateDeptBtnActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String id = deptIDTextField.getText().toString();
        if(!id.isEmpty()){
            DepratmentModel dept = db.searchDepartment(Integer.parseInt(id));
            if(dept!=null)
                JOptionPane.showMessageDialog(this, dept.toString());
            else
                JOptionPane.showMessageDialog(this, "No Record Found");
        } else {
            JOptionPane.showMessageDialog(this, "Enter Valid Department ID");
            
        }
    }//GEN-LAST:event_searchActionPerformed

    private void departmentCrud_backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentCrud_backBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StaffMenus().setVisible(true);
    }//GEN-LAST:event_departmentCrud_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDeptBtn;
    private javax.swing.JButton deleteDeptBtn;
    private javax.swing.JButton departmentCrud_backBtn;
    private javax.swing.JTextField deptIDTextField;
    private javax.swing.JTextField deptNameTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton search;
    private javax.swing.JButton updateDeptBtn;
    // End of variables declaration//GEN-END:variables
}
